# ---------------------------
# Configuracion de la base de datos
# ---------------------------


#datos para la conexion a la bdd
spring.datasource.url=jdbc:mysql://${DB_HOST:nutriapp-mysql-nutriapp.j.aivencloud.com}:${DB_PORT:22041}/NutriApp?sslMode=REQUIRED
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD}

# Driver JDBC que se usa para conectarse a MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#------------------------------------------------------------------------------------------------------------

# Relacionado al envio de mail debido a que se bloquean por usar version gratuita
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=nutriapp1oficial@gmail.com
brevo.sender.name=NutriApp

# ------------------------------------------------------------------------------------------------------------
# ---------------------------
# Configuracion de Hibernate / JPA
# ---------------------------

# Indica que debe hacer Hibernate con las tablas:
# Opciones:
# - none: No hace nada.
# - validate: Verifica que las tablas existan y coincidan con las entidades (no crea ni actualiza).
# - update: Crea tablas nuevas o modifica las existentes sin borrar datos.
# - create: Borra todo y crea las tablas de cero al arrancar (cuidado! se pierden datos).
# - create-drop: Crea las tablas al iniciar y las borra al apagar la app.
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola las consultas SQL que ejecuta Hibernate (muy util para debug)
spring.jpa.show-sql=true

# Dialecto de base de datos: le indica a Hibernate como generar las consultas SQL especificas para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#------------------------------------------------------------------------------------------------------------
spring.ai.vertex.ai.gemini.project-id=nutriapp-61192
spring.ai.vertex.ai.gemini.location=global
spring.ai.vertex.ai.gemini.chat.options.model=gemini-3.5-flash
#------------------------------------------------------------------------------------------------------------
# ---------------------------
# Configuracion para los mails
# ---------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nutriappestudiantes@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com  //esto es soluciona el error de conexiones TLS/SSL que algunos antivirus pueden ocacionar o redes universitarias
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
#------------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------------
# api key para utilizar endpoints de la api externa
fdc.api.key=${FDC_API_KEY}
#------------------------------------------------------------------------------------------------------------


#------------------------------------------------------------------------------------------------------------
# clave secreta que requerimos para poder utilizar el JWT
jwt.secret=${JWT_SECRET}

debug=true
#------------------------------------------------------------------------------------------------------------

