# ---------------------------
# Configuración de la base de datos
# ---------------------------

# URL de conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/NutriApp

# Usuario de la base de datos
spring.datasource.username=root

# Contraseña de la base de datos
spring.datasource.password=Juanjuli2*

# Driver JDBC que se usa para conectarse a MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#------------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------------
# ---------------------------
# Configuración de Hibernate / JPA
# ---------------------------

# Indica qué debe hacer Hibernate con las tablas:
# Opciones:
# - none: No hace nada.
# - validate: Verifica que las tablas existan y coincidan con las entidades (no crea ni actualiza).
# - update: Crea tablas nuevas o modifica las existentes sin borrar datos.
# - create: Borra todo y crea las tablas de cero al arrancar (¡cuidado! se pierden datos).
# - create-drop: Crea las tablas al iniciar y las borra al apagar la app.
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola las consultas SQL que ejecuta Hibernate (muy útil para debug)
spring.jpa.show-sql=true

# Dialecto de base de datos: le indica a Hibernate cómo generar las consultas SQL específicas para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#------------------------------------------------------------------------------------------------------------


#------------------------------------------------------------------------------------------------------------
# ---------------------------
# Configuracion para los mails
# ---------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nutriappestudiantes@gmail.com
spring.mail.password=pcdf uoay iifl rulq
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com  //esto es soluciona el error de conexiones TLS/SSL que algunos antivirus pueden ocacionar o redes universitarias

#------------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------------
# api key para utilizar endpoints de la api externa
fdc.api.key=Nh6CDqi5WAIY5gfgRKemDUHXiDmFtqdDPppzzPq9
#------------------------------------------------------------------------------------------------------------


#------------------------------------------------------------------------------------------------------------
# clave secreta que requerimos para poder utilizar el JWT
jwt.secret=MiClaveS3cretaJWT-SuperSegura_ConSimbolos123!

debug=true
#------------------------------------------------------------------------------------------------------------
